#!/usr/bin/env bash
# Target-node setup: provisions an Ubuntu 24.04 VM so it can host the
# containerized mywebapp service.
#
# Idempotent — safe to run multiple times. The script:
#   1. installs Docker Engine and PostgreSQL
#   2. creates the application database and unprivileged DB user
#   3. installs nginx as the reverse proxy
#   4. drops a docker-compose.yml, config.toml and nginx config into
#      /opt/mywebapp/
#   5. installs the mywebapp.service systemd unit that controls the container
#   6. configures an ssh-only deploy user with permission to restart the unit
#
# Run as root:   sudo bash target-node-setup.sh
#
set -euo pipefail

# --- configuration ----------------------------------------------------------
DEPLOY_USER="deploy"
APP_DIR="/opt/mywebapp"
DB_NAME="mywebapp"
DB_USER="mywebapp"
DB_PASSWORD="${DB_PASSWORD:-mywebapp_$(openssl rand -hex 8)}"
GHCR_IMAGE_DEFAULT="${GHCR_IMAGE_DEFAULT:-ghcr.io/example/example:stable}"

# --- 1. base packages -------------------------------------------------------
echo "[setup] installing base packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y --no-install-recommends \
    ca-certificates curl gnupg lsb-release \
    nginx postgresql sudo openssh-server

# --- 2. Docker Engine -------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    echo "[setup] installing Docker Engine..."
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
        > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y --no-install-recommends \
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
systemctl enable --now docker

# --- 3. PostgreSQL: database and unprivileged user --------------------------
echo "[setup] configuring PostgreSQL..."
systemctl enable --now postgresql
sudo -u postgres psql <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
  END IF;
END \$\$;
SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
  WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}')
  \\gexec
SQL

# Allow the container to reach the host's postgres via the docker bridge.
PG_CONF=$(sudo -u postgres psql -tAc "SHOW config_file")
PG_HBA=$(sudo -u postgres psql -tAc "SHOW hba_file")
grep -q "^listen_addresses *= *'\*'" "$PG_CONF" \
    || sed -i "s/^#\?listen_addresses.*/listen_addresses = '*'/" "$PG_CONF"
grep -q "host    ${DB_NAME}    ${DB_USER}    172.16.0.0/12" "$PG_HBA" \
    || echo "host    ${DB_NAME}    ${DB_USER}    172.16.0.0/12    scram-sha-256" >> "$PG_HBA"
systemctl reload postgresql

# --- 4. deploy user with restricted sudo ------------------------------------
echo "[setup] creating deploy user..."
id "$DEPLOY_USER" &>/dev/null || useradd -m -s /bin/bash "$DEPLOY_USER"
usermod -aG docker "$DEPLOY_USER"

cat > /etc/sudoers.d/deploy <<EOF
${DEPLOY_USER} ALL=(root) NOPASSWD: \
    /bin/systemctl daemon-reload, \
    /bin/systemctl restart mywebapp.service, \
    /bin/systemctl stop mywebapp.service, \
    /bin/systemctl start mywebapp.service, \
    /bin/systemctl status mywebapp.service, \
    /usr/bin/docker pull *, \
    /usr/bin/docker image prune -f, \
    /usr/sbin/nginx -t, \
    /bin/systemctl reload nginx
EOF
chmod 0440 /etc/sudoers.d/deploy

# --- 5. application directory and configs -----------------------------------
echo "[setup] installing application configs in ${APP_DIR}..."
mkdir -p "$APP_DIR"

cat > "$APP_DIR/config.toml" <<EOF
# Generated by target-node-setup.sh. Mounted read-only into the container.
[server]
host = "0.0.0.0"
port = 5200

[database]
host = "host.docker.internal"   # see extra_hosts in docker-compose.yml
port = 5432
name = "${DB_NAME}"
user = "${DB_USER}"
password = "${DB_PASSWORD}"
EOF
chown root:"$DEPLOY_USER" "$APP_DIR/config.toml"
chmod 0640 "$APP_DIR/config.toml"

cat > "$APP_DIR/docker-compose.yml" <<EOF
# Generated by target-node-setup.sh. The systemd unit drives this file.
name: mywebapp
services:
  app:
    image: \${IMAGE_REF:-${GHCR_IMAGE_DEFAULT}}
    environment:
      MYWEBAPP_CONFIG: /etc/mywebapp/config.toml
    volumes:
      - ${APP_DIR}/config.toml:/etc/mywebapp/config.toml:ro
    ports:
      - "127.0.0.1:5200:5200"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
EOF
chown root:"$DEPLOY_USER" "$APP_DIR/docker-compose.yml"
chmod 0640 "$APP_DIR/docker-compose.yml"

# --- 6. nginx reverse proxy -------------------------------------------------
echo "[setup] configuring nginx..."
cat > /etc/nginx/sites-available/mywebapp <<'EOF'
upstream mywebapp_backend {
    server 127.0.0.1:5200;
}

server {
    listen 80 default_server;
    server_name _;

    access_log /var/log/nginx/mywebapp_access.log;
    error_log  /var/log/nginx/mywebapp_error.log;

    location = / {
        proxy_pass http://mywebapp_backend;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /items {
        proxy_pass http://mywebapp_backend;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 404;
    }
}
EOF
ln -sf /etc/nginx/sites-available/mywebapp /etc/nginx/sites-enabled/mywebapp
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

# --- 7. systemd unit that controls the container ---------------------------
echo "[setup] installing mywebapp.service..."
cat > /etc/systemd/system/mywebapp.service <<EOF
[Unit]
Description=mywebapp containerized service
After=docker.service postgresql.service network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${APP_DIR}
EnvironmentFile=-${APP_DIR}/.env
ExecStartPre=/usr/bin/docker compose pull
ExecStart=/usr/bin/docker compose up -d --remove-orphans
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable mywebapp.service

cat <<EOF

================================================================
 Target node provisioned.
 Deploy user            : ${DEPLOY_USER}
 Application directory  : ${APP_DIR}
 DB user / db / password: ${DB_USER} / ${DB_NAME} / ${DB_PASSWORD}

 Next steps:
  1. Add the runner's SSH public key to /home/${DEPLOY_USER}/.ssh/authorized_keys
  2. Add GitHub secrets in the repo:
       TARGET_HOST     = (public IP/hostname of this VM)
       TARGET_USER     = ${DEPLOY_USER}
       TARGET_SSH_KEY  = (matching private key)
  3. Push an annotated tag (e.g. v1.0.0) to trigger the first deploy.
================================================================
EOF
